[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4" }
rusqlite = { version = "0.28.0", features = ["chrono", "serde_json"] }

storage = { version = "0.1", path = "../storage" }
