name: Publish
on:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
    - name: Authenticate
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        load: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Run and Publish
      run: |
        mkdir result
        docker run --mount type=bind,source="$(pwd)/result",target=/result -t --rm ghcr.io/conradev/energy-data:latest assemble /result/energy.db
    - uses: actions/upload-artifact@v3
      with:
        name: energy.db
        path: result/energy.db
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

